# Trigger on the main branch
trigger:
- main

# Use an agent pool
pool: agent

steps:
# Set JAVA_HOME environment variable for Maven
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
  displayName: 'Set JAVA_HOME for Maven'

# Maven Task for clean, compile, and package
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean compile package'  # Run clean, compile, and package in a single task
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'  # Use the JAVA_HOME set in the previous step
    mavenVersionOption: 'Default'  # Use the default Maven version
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
