# Trigger on the main branch
trigger:
- main

# Use a Microsoft-hosted agent pool with Ubuntu
pool:
  vmImage: 'ubuntu-latest'  # You can also use 'windows-latest' or 'macos-latest'

steps:
# Maven Task for clean, compile, and package
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'  # The location of your pom.xml file
    goals: 'clean compile package'  # Run clean, compile, and package in a single task
    publishJUnitResults: true  # Publish JUnit results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Location of test result files
    javaHomeOption: 'JDKVersion'  # Use the JDK version set below
    mavenVersionOption: 'Default'  # Use the default Maven version
    mavenAuthenticateFeed: false  # Do not authenticate Maven feed (if not needed)
    effectivePomSkip: false  # Skip generating the effective POM (set to false if you want it)
    sonarQubeRunAnalysis: false  # Do not run SonarQube analysis (set to true if needed)

# Install JDK 1.11 (this ensures JDK 11 is available for the build)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '1.11'  # Install JDK 11
    jdkArchitecture: 'x64'  # Ensure x64 architecture is used
