# Trigger on the main branch
trigger:
- main

# Use an agent pool
pool: agent

steps:
# Maven Task for compile and package
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean compile package'  # Run clean, compile, and package in a single task
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'  # Automatically use the JDK version set below
    mavenVersionOption: 'Default'  # Use the default Maven version
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# Set JDK version and architecture
- task: UseJavaVersion@0
  inputs:
    versionSpec: '1.11'
    jdkArchitectureOption: 'x64'

