# Trigger the pipeline on changes to the 'main' branch
trigger:
- main

# Define the build agent pool
pool:
  vmImage: ubuntu-latest

# Define pipeline steps
steps:
# Step 1: Compile the project
- task: Maven@3
  displayName: 'Compile Java Project'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'  # Increase Maven memory for large projects
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    goals: 'compile'

# Step 2: Package the project
- task: Maven@3
  displayName: 'Package Java Project'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
